import { createSignal, onMount } from 'solid-js';
import { Activity, Database, Gauge, ShieldCheck } from 'lucide-solid';
import { Button, Dialog, Panel, Select, Toggle } from '../../components/ui';
import { studioApi } from '../../api/invoke';
import type { StudioSettings } from '../../types';

export default function SettingsPage() {
  const [policy, setPolicy] = createSignal<StudioSettings['processPolicy']>('Economy');
  const [suspend, setSuspend] = createSignal(true); const [cacheLimit, setCacheLimit] = createSignal<StudioSettings['cacheLimitMb']>(100); const [onboardingCompleted, setOnboardingCompleted] = createSignal(false); const [connectedProviders, setConnectedProviders] = createSignal<string[]>([]);
  const [status, setStatus] = createSignal(''); const [diagnostics, setDiagnostics] = createSignal('');
  onMount(async () => { if (!('__TAURI_INTERNALS__' in window)) return; try { const settings = await studioApi.settings(); setPolicy(settings.processPolicy); setSuspend(settings.suspendBackground); setCacheLimit(settings.cacheLimitMb); setOnboardingCompleted(settings.onboardingCompleted); setConnectedProviders(settings.connectedProviders ?? []); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to load settings'); } });
  async function save() { try { await studioApi.saveSettings({ processPolicy: policy(), suspendBackground: suspend(), cacheLimitMb: cacheLimit(), onboardingCompleted: onboardingCompleted(), connectedProviders: connectedProviders() }); setStatus('Settings saved'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Save failed'); } }
  async function openDiagnostics() { try { const [capabilities, stats] = await Promise.all([studioApi.capabilities(), studioApi.runtimeStats()]); setDiagnostics(JSON.stringify({ capabilities, stats }, null, 2)); } catch (error) { setDiagnostics(error instanceof Error ? error.message : 'Diagnostics unavailable'); } }
  return <div class="page settings-page"><header class="page-heading"><h1>Settings</h1><p>Performance, OMP runtime, storage, and diagnostics.</p></header><div class="settings-grid"><Panel title="OMP runtime"><div class="settings-body"><label><span><Gauge /><strong>Process policy</strong><small>Economy keeps the active session and one recent session warm.</small></span><Select label="Process policy" value={policy()} options={['Economy', 'Balanced', 'Parallel']} onChange={value => setPolicy(value as StudioSettings['processPolicy'])} /></label><label><span><Activity /><strong>Suspend background activity</strong><small>Stop non-essential refreshes while minimized.</small></span><Toggle checked={suspend()} onChange={setSuspend} label="Suspend background activity" /></label> </div></Panel><Panel title="Storage"><div class="settings-body"><label><span><Database /><strong>Cache limit</strong><small>Usage and catalog cache, excluding OMP session data.</small></span><Select label="Cache limit" value={`${cacheLimit()} MB`} options={['50 MB', '100 MB', '200 MB']} onChange={value => setCacheLimit(Number.parseInt(value) as StudioSettings['cacheLimitMb'])} /></label></div></Panel><Panel title="Security"><div class="settings-body"><p><ShieldCheck size={18} class="success" />Credentials stay in OMP and are never sent to the frontend.</p></div></Panel><div class="settings-actions"><Button variant="solid" tone="accent" onClick={() => void save()}>Save settings</Button><Button onClick={() => void openDiagnostics()}>Open diagnostics</Button></div>{status() && <small>{status()}</small>}</div><Dialog open={Boolean(diagnostics())} title="OMP Studio diagnostics" onClose={() => setDiagnostics('')}><pre class="file-inspector"><code>{diagnostics()}</code></pre></Dialog></div>;
}
