import { For, Show, createResource, createSignal, onCleanup, onMount } from 'solid-js';
import { Clock3, Gauge, RefreshCw, ShieldCheck } from 'lucide-solid';
import { studioApi } from '../../api/invoke';
import { Badge, Button, Dialog, EmptyState, Panel, ProgressBar } from '../../components/ui';

export default function UsagePage() {
  const [loadError, setLoadError] = createSignal('');
  const fetchUsage = async () => { setLoadError(''); if (!('__TAURI_INTERNALS__' in window)) { setLoadError('Usage is available in the installed OMP Studio application.'); return null; } try { return await studioApi.usage(undefined, false); } catch (error) { setLoadError(error instanceof Error ? error.message : 'OMP did not return usage data.'); return null; } };
  const [usage, { refetch }] = createResource(fetchUsage); const [accountId, setAccountId] = createSignal(''); const [confirming, setConfirming] = createSignal(false); const [resetState, setResetState] = createSignal(''); const [suspendBackground, setSuspendBackground] = createSignal(true);
  onMount(() => { if ('__TAURI_INTERNALS__' in window) void studioApi.settings().then(settings => setSuspendBackground(settings.suspendBackground)); const refreshAllowed = () => !suspendBackground() || document.visibilityState === 'visible'; const timer = window.setInterval(() => { if (refreshAllowed()) void refetch(); }, 60_000); const visibility = () => { if (document.visibilityState === 'visible') void refetch(); }; document.addEventListener('visibilitychange', visibility); onCleanup(() => { clearInterval(timer); document.removeEventListener('visibilitychange', visibility); }); });
  const accounts = () => usage()?.providers.flatMap(provider => provider.accounts) ?? []; const selected = () => accounts().find(item => item.credentialId === accountId()) ?? accounts().find(item => item.activeForSession) ?? accounts()[0]; const provider = () => usage()?.providers.find(item => item.accounts.some(account => account.credentialId === selected()?.credentialId));
  async function consumeReset() { const current = selected(); const credit = current?.resetCredits?.credits.find(item => item.applicable); if (!current || !credit) { setResetState('No applicable saved reset is available.'); setConfirming(false); return; } setResetState('Submitting…'); try { const result = await studioApi.consumeReset(current.credentialId, credit.id, crypto.randomUUID()); setResetState(result); setConfirming(false); await refetch(); } catch (error) { setResetState(error instanceof Error ? error.message : 'Reset failed'); } }
  return <div class="page usage-page"><header class="page-heading usage-heading"><div><h1>Usage & limits</h1><p>Provider limits are shown per account and are never combined.</p></div><Button onClick={() => refetch()}><RefreshCw size={16} />Refresh</Button></header><Show when={usage()} fallback={<Show when={loadError()} fallback={<div class="usage-skeleton" />}><EmptyState title="Usage unavailable" message={loadError()} /></Show>}><Show when={selected()} fallback={<EmptyState title="Usage unavailable" message="Connect a subscription provider to see account limits." />}><div class="usage-grid"><section><Panel><div class="account-header"><div class="provider-logo"><Gauge /></div><div><h2>{provider()?.providerName ?? 'Provider'}</h2><p>{selected()!.displayLabel}</p></div><Show when={accounts().length > 1}><select aria-label="Usage account" value={selected()!.credentialId} onChange={event => setAccountId(event.currentTarget.value)}><For each={accounts()}>{account => <option value={account.credentialId}>{account.displayLabel}</option>}</For></select></Show><Badge tone={usage()!.stale ? 'warning' : selected()!.activeForSession ? 'success' : 'default'}>{usage()!.stale ? 'Stale data' : selected()!.activeForSession ? 'Active session' : 'Account'}</Badge></div></Panel><For each={selected()!.limits}>{limit => <Panel class="limit-card"><header><div><h2>{limit.label}</h2><small>{limit.resetsAt ? `Resets ${limit.resetsAt}` : 'Reset time unavailable'}</small></div><strong>{Math.round(limit.usedPercent)}%</strong></header><ProgressBar label={limit.label} value={limit.usedPercent} tone={limit.usedPercent >= 85 ? 'warning' : 'accent'} /></Panel>}</For></section><aside><Panel title="Saved resets"><div class="reset-summary"><strong>{selected()!.resetCredits?.available ?? 0}</strong><span>saved resets available</span><p>Saved rate-limit resets are consumed only after explicit confirmation.</p><Button disabled={!selected()!.resetCredits?.credits.some(credit => credit.applicable)} onClick={() => setConfirming(true)} variant="solid" tone="accent">Use a saved reset</Button>{resetState() && <small>{resetState()}</small>}</div></Panel><Panel title="Data source"><div class="source-summary"><p><ShieldCheck size={16} /> Credentials remain managed by OMP.</p><p><Clock3 size={16} /> Last updated {new Date(usage()!.fetchedAt).toLocaleTimeString()}</p><p>Source: {usage()!.source}</p></div></Panel></aside></div></Show></Show><Dialog open={confirming()} title="Use one saved rate-limit reset?" onClose={() => setConfirming(false)} actions={<><Button onClick={() => setConfirming(false)}>Cancel</Button><Button variant="solid" tone="danger" onClick={consumeReset}>Use reset</Button></>}><div class="reset-dialog-copy"><dl><dt>Account</dt><dd>{selected()?.displayLabel}</dd><dt>Saved resets</dt><dd>{selected()?.resetCredits?.available ?? 0} available</dd></dl><p>This action consumes one saved reset and cannot be undone.</p></div></Dialog></div>;
}
